# .github/ISSUE_TEMPLATE/config.yml
blank_issues_enabled: false
contact_links:
  - name: Security Issue
    url: https://github.com/frivas/roots/security/policy
    about: Please report security vulnerabilities here.
